/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface PredicateClientInterface extends utils.Interface {
  functions: {
    "getPolicy()": FunctionFragment;
    "getPredicateManager()": FunctionFragment;
    "setPolicy(string)": FunctionFragment;
    "setPredicateManager(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getPolicy"
      | "getPredicateManager"
      | "setPolicy"
      | "setPredicateManager"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "getPolicy", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getPredicateManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPolicy",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPredicateManager",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "getPolicy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPredicateManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPolicy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPredicateManager",
    data: BytesLike
  ): Result;

  events: {};
}

export interface PredicateClient extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PredicateClientInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getPolicy(overrides?: CallOverrides): Promise<[string]>;

    getPredicateManager(overrides?: CallOverrides): Promise<[string]>;

    setPolicy(
      _policyID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPredicateManager(
      _predicateManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getPolicy(overrides?: CallOverrides): Promise<string>;

  getPredicateManager(overrides?: CallOverrides): Promise<string>;

  setPolicy(
    _policyID: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPredicateManager(
    _predicateManager: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getPolicy(overrides?: CallOverrides): Promise<string>;

    getPredicateManager(overrides?: CallOverrides): Promise<string>;

    setPolicy(
      _policyID: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPredicateManager(
      _predicateManager: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getPolicy(overrides?: CallOverrides): Promise<BigNumber>;

    getPredicateManager(overrides?: CallOverrides): Promise<BigNumber>;

    setPolicy(
      _policyID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPredicateManager(
      _predicateManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getPolicy(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPredicateManager(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setPolicy(
      _policyID: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPredicateManager(
      _predicateManager: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
