/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBeacon,
  IBeaconInterface,
} from "../../../large/0x67c58996670ad4afc9cf74f3367a6c430da0b605.sol/IBeacon";

const _abi = [
  {
    inputs: [],
    name: "implementation",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IBeacon__factory {
  static readonly abi = _abi;
  static createInterface(): IBeaconInterface {
    return new Interface(_abi) as IBeaconInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IBeacon {
    return new Contract(address, _abi, runner) as unknown as IBeacon;
  }
}
