/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  Abs_AuctionRegistrar_int,
  Abs_AuctionRegistrar_intInterface,
} from "../../../large/0xcf40d43dbfb4a586bc5ba9ddc50c5204c0542516.sol/Abs_AuctionRegistrar_int";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_hash",
        type: "bytes32",
      },
    ],
    name: "entries",
    outputs: [
      {
        internalType: "enum Abs_AuctionRegistrar_int.Mode",
        name: "",
        type: "uint8",
      },
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_hash",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "revealP",
        type: "uint256",
      },
    ],
    name: "startAuction_ge0",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_hash",
        type: "bytes32",
      },
    ],
    name: "state_pln",
    outputs: [
      {
        internalType: "enum Abs_AuctionRegistrar_int.Mode",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class Abs_AuctionRegistrar_int__factory {
  static readonly abi = _abi;
  static createInterface(): Abs_AuctionRegistrar_intInterface {
    return new utils.Interface(_abi) as Abs_AuctionRegistrar_intInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Abs_AuctionRegistrar_int {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as Abs_AuctionRegistrar_int;
  }
}
