/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  AbstractGWF_int,
  AbstractGWF_intInterface,
} from "../../../large/0xcf40d43dbfb4a586bc5ba9ddc50c5204c0542516.sol/AbstractGWF_int";

const _abi = [
  {
    inputs: [],
    name: "auctionContract",
    outputs: [
      {
        internalType: "contract Abs_AuctionRegistrar_int",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "base",
    outputs: [
      {
        internalType: "contract AbstractBaseR_int",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "controllerContract",
    outputs: [
      {
        internalType: "contract AbstractETHRegController_int",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "_dom",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "command",
        type: "uint256",
      },
    ],
    name: "domainReport",
    outputs: [
      {
        internalType: "uint256",
        name: "report",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "gwpc",
        type: "address",
      },
      {
        internalType: "address",
        name: "ptc",
        type: "address",
      },
      {
        internalType: "address",
        name: "gwfc",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "structure",
        type: "bytes",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "ens",
    outputs: [
      {
        internalType: "contract AbstractTM_ENS_int",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getGWF",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_dHash",
        type: "bytes32",
      },
    ],
    name: "getGWProxy",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_dHash",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "getIsOwner",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_domainHash",
        type: "bytes32",
      },
    ],
    name: "getOwner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_domainHash",
        type: "bytes32",
      },
    ],
    name: "getProxyToken",
    outputs: [
      {
        internalType: "address",
        name: "p",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "resolverContract",
    outputs: [
      {
        internalType: "contract AbstractTM_Resolver_int",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "reverseContract",
    outputs: [
      {
        internalType: "contract AbstractRR_int",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "tld",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class AbstractGWF_int__factory {
  static readonly abi = _abi;
  static createInterface(): AbstractGWF_intInterface {
    return new utils.Interface(_abi) as AbstractGWF_intInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AbstractGWF_int {
    return new Contract(address, _abi, signerOrProvider) as AbstractGWF_int;
  }
}
