/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ApeRouter,
  ApeRouterInterface,
} from "../../../medium/0x4b7b3e661c9a2de1d09382e4cff6a8fde16d061a.sol/ApeRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "AllowedProxies",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ApeRouter__factory {
  static readonly abi = _abi;
  static createInterface(): ApeRouterInterface {
    return new utils.Interface(_abi) as ApeRouterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ApeRouter {
    return new Contract(address, _abi, signerOrProvider) as ApeRouter;
  }
}
