/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { NeuroXOracle__factory } from "./NeuroXOracle__factory";
export { Ownable__factory } from "./Ownable__factory";
