/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  InterfaceLP,
  InterfaceLPInterface,
} from "../../../large/0xefb8957fe2f4ad82554852fbf73d7aee3a6e63a3.sol/InterfaceLP";

const _abi = [
  {
    inputs: [],
    name: "sync",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class InterfaceLP__factory {
  static readonly abi = _abi;
  static createInterface(): InterfaceLPInterface {
    return new utils.Interface(_abi) as InterfaceLPInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): InterfaceLP {
    return new Contract(address, _abi, signerOrProvider) as InterfaceLP;
  }
}
